#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check21="2.1"
CHECK_TITLE_check21="[check21] Ensure CloudTrail is enabled in all regions (Scored)"
CHECK_SCORED_check21="SCORED"
CHECK_TYPE_check21="LEVEL1"
CHECK_SEVERITY_check21="High"
CHECK_ASFF_TYPE_check21="Software and Configuration Checks/Industry and Regulatory Standards/CIS AWS Foundations Benchmark"
CHECK_ASFF_RESOURCE_TYPE_check21="AwsCloudTrailTrail"
CHECK_ALTERNATE_check201="check21"

check21(){
  trail_count=0
  if [ -z $INCLUDE_SHADOW_TRAILS ] || [ "$INCLUDE_SHADOW_TRAILS" != "true" ]; then
    SHADOW_TRAIL_FLAG="--no-include-shadow-trails"
  else
    SHADOW_TRAIL_FLAG="--include-shadow-trails"
  fi
  # "Ensure CloudTrail is enabled in all regions (Scored)"
	for regx in $REGIONS; do
		LIST_OF_TRAILS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $regx --query 'trailList[*].Name' --output text $SHADOW_TRAIL_FLAG)
		if [[ $LIST_OF_TRAILS ]];then
			for trail in $LIST_OF_TRAILS;do
				trail_count=$((trail_count + 1))
				MULTIREGION_TRAIL_STATUS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $regx --query 'trailList[*].IsMultiRegionTrail' --output text --trail-name-list $trail)
				if [[ "$MULTIREGION_TRAIL_STATUS" == 'False' ]];then
					textFail "$trail trail in $regx is not enabled in multi region mode"
				else
					textPass "$trail trail in $regx is enabled for all regions"
				fi
			done
		fi
	done

	if [[ $trail_count == 0 ]]; then
	  ORG_TRAIL=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region us-east-1 | jq '.trailList[] | select(.IsMultiRegionTrail and .IsOrganizationTrail) | .Name' | sed 's/"//g')
	  if [[ $ORG_TRAIL != "" ]]; then
      textPass "$ORG_TRAIL trail in $regx is enabled for all regions"
    else
      textFail "No CloudTrail trails were found in the account"
    fi
  fi
}